/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "SModalAlertDelegate-Protocol.h"

@class NSMutableArray, NSString, SAppList, SBulletinBanner, SModalAlert, SRootScrollView, SStartScrollView, SVolumeHUD, SpringBoard, UIWindow;

@interface Strife : NSObject <SModalAlertDelegate>
{
    SpringBoard *springboard;
    UIWindow *window;
    NSString *theme;
    NSMutableArray *bulletinQueue;
    NSMutableArray *alertQueue;
    SModalAlert *alert;
    SRootScrollView *rootScrollView;
    SAppList *appList;
    SStartScrollView *startScrollView;
    SVolumeHUD *volumeHUD;
    SBulletinBanner *currentBulletinBanner;
    BOOL shouldShowLockscreen;
}

+ (id)sharedInstance;
@property(retain, nonatomic) SModalAlert *alert; // @synthesize alert;
@property BOOL shouldShowLockscreen; // @synthesize shouldShowLockscreen;
@property(retain, nonatomic) NSString *theme; // @synthesize theme;
@property(retain, nonatomic) SBulletinBanner *currentBulletinBanner; // @synthesize currentBulletinBanner;
@property(retain, nonatomic) SVolumeHUD *volumeHUD; // @synthesize volumeHUD;
@property(nonatomic) __weak SpringBoard *springboard; // @synthesize springboard;
@property(retain, nonatomic) SStartScrollView *startScrollView; // @synthesize startScrollView;
@property(retain, nonatomic) SAppList *appList; // @synthesize appList;
@property(retain, nonatomic) SRootScrollView *rootScrollView; // @synthesize rootScrollView;
@property(nonatomic) __weak UIWindow *window; // @synthesize window;
- (void).cxx_destruct;
- (void)dealloc;
- (unsigned int)loadFonts;
- (void)showAllExcept:(id)arg1;
- (void)hideAllExcept:(id)arg1;
- (void)updateAllBadges;
- (void)updateBadge:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)showModalAlertWithAlertItem:(id)arg1;
- (void)removeNextBulletin;
- (void)removeBulletinFromQueue:(id)arg1 isExistingBanner:(BOOL)arg2;
- (void)addBulletinToQueue:(id)arg1;
- (void)showBannerForBulletin:(id)arg1;
- (void)showVolumeHUD;
- (void)volumeChanged;
- (void)ringerStateChanged;
- (void)hudShouldShowControls:(BOOL)arg1;
- (void)nowPlayingInfoChanged;
- (void)applicationPlayingChanged;
- (void)changeTrack:(int)arg1;
- (id)lockKeyPadBackgroundColor;
- (id)lockKeyPadButtonColor;
- (id)contrastColor;
- (id)backgroundColor;
- (id)foregroundTextColor;
- (id)theColor;
- (id)accentColor;
- (id)initWithWindow:(id)arg1 springBoard:(id)arg2;

@end

